wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698474305.54911
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 16
      - 23
      4: 3.8.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
