wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.5
    cli_version: 0.15.12
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698475446.064289
    t:
      1:
      - 55
      3:
      - 23
      4: 3.8.5
      5: 0.15.12
      8:
      - 3
      - 5
      13: windows-amd64
